"""initial schema

Revision ID: f1e8e744467b
Revises: 
Create Date: 2026-06-11 07:30:22.192765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1e8e744467b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_source_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('log_backend_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('failure_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('application_name', sa.String(), nullable=True),
    sa.Column('component_name', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('file_trace_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('event_created_ts', sa.DateTime(), nullable=True),
    sa.Column('event_inserted_ts', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rca_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('new', 'triaged', 'analyzing', 'analyzed', 'assigned', 'resolved', 'recurring', name='case_status'), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('component_name', sa.String(), nullable=True),
    sa.Column('error_pattern', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('likely_fix', sa.Text(), nullable=True),
    sa.Column('affected_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_path', sa.Text(), nullable=True),
    sa.Column('impact_count', sa.Integer(), nullable=False),
    sa.Column('cw_log_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('root_cause_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('fix_notes', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'signature_hash', name='uq_signature_project_hash')
    )
    op.create_table('case_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['rca_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_failure_records',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('failure_record_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['rca_cases.id'], ),
    sa.ForeignKeyConstraint(['failure_record_id'], ['failure_records.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'failure_record_id')
    )
    op.create_table('case_signature_links',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('signature_id', sa.UUID(), nullable=False),
    sa.Column('matched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['rca_cases.id'], ),
    sa.ForeignKeyConstraint(['signature_id'], ['root_cause_signatures.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'signature_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_signature_links')
    op.drop_table('case_failure_records')
    op.drop_table('case_activity')
    op.drop_table('root_cause_signatures')
    op.drop_table('rca_cases')
    op.drop_table('failure_records')
    op.drop_table('projects')
    # ### end Alembic commands ###
